// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: nutrition_recipe.
// - Entity ID: 102019ac25e7e4071f085761ad11b897d1b.
// - Entity Version: 102019aca8871857d468edae750e17b27cf.
// - Task ID: 69299b9cbe7b168045cb8253.
// - Task Root ID: 6927837783045624aba5d052.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for NutritionRecipeMealType
 */
export enum NutritionRecipeMealType {
  Unspecified = 0,
  Breakfast = 1,
  Lunch = 2,
  Dinner = 3,
  Snack = 4,
}



/**
 * Interface for NutritionRecipeModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface NutritionRecipeModel {
  id: string;
  name: string;
  description?: string | null;
  meal_type: NutritionRecipeMealType;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
  ingredients: string[];
  instructions: string;
  image_url?: string | null;
  prep_time_minutes: number;
  is_premium: boolean;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for NutritionRecipe entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class NutritionRecipeORM {
  private static instance: NutritionRecipeORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac25e7e4071f085761ad11b897d1b';
    this.entityName = 'nutrition_recipe';
    this.entityVersion = '102019aca8871857d468edae750e17b27cf';
    this.taskId = '69299b9cbe7b168045cb8253';
    this.taskRootId = '6927837783045624aba5d052';
  }

  /**
   * Get singleton instance of NutritionRecipeORM
   */
  public static getInstance(): NutritionRecipeORM {
    if (!NutritionRecipeORM.instance) {
      NutritionRecipeORM.instance = new NutritionRecipeORM();
    }
    
    return NutritionRecipeORM.instance;
  }

  /**
   * Get all NutritionRecipe records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllNutritionRecipe(): Promise<NutritionRecipeModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new NutritionRecipe record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertNutritionRecipe(data: NutritionRecipeModel[]): Promise<NutritionRecipeModel[]> {
    const structured = data.map((item) => CreateData(NutritionRecipeModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all NutritionRecipe records
   */
  async purgeAllNutritionRecipe(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List NutritionRecipe records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listNutritionRecipe(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[NutritionRecipeModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get nutrition_recipe by Id index
   * This function gets data by index.
   */
  async getNutritionRecipeById(
    id: string,
  ): Promise<NutritionRecipeModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_recipe by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionRecipeById(
    id: string,
    data: NutritionRecipeModel
  ): Promise<NutritionRecipeModel[]> {
    const index = createIndexId(
      id
    );

    const values = NutritionRecipeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_recipe by Id index
   */
  async deleteNutritionRecipeById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get nutrition_recipe by MealType index
   * This function gets data by index.
   */
  async getNutritionRecipeByMealType(
    meal_type: NutritionRecipeMealType,
  ): Promise<NutritionRecipeModel[]> {
    const index = createIndexMealType(
      meal_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_recipe by MealType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionRecipeByMealType(
    meal_type: NutritionRecipeMealType,
    data: NutritionRecipeModel
  ): Promise<NutritionRecipeModel[]> {
    const index = createIndexMealType(
      meal_type
    );

    const values = NutritionRecipeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_recipe by MealType index
   */
  async deleteNutritionRecipeByMealType(
    meal_type: NutritionRecipeMealType
  ): Promise<void> {
    const index = createIndexMealType(
      meal_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get nutrition_recipe by IsPremium index
   * This function gets data by index.
   */
  async getNutritionRecipeByIsPremium(
    is_premium: boolean,
  ): Promise<NutritionRecipeModel[]> {
    const index = createIndexIsPremium(
      is_premium
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_recipe by IsPremium index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionRecipeByIsPremium(
    is_premium: boolean,
    data: NutritionRecipeModel
  ): Promise<NutritionRecipeModel[]> {
    const index = createIndexIsPremium(
      is_premium
    );

    const values = NutritionRecipeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_recipe by IsPremium index
   */
  async deleteNutritionRecipeByIsPremium(
    is_premium: boolean
  ): Promise<void> {
    const index = createIndexIsPremium(
      is_premium
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get nutrition_recipe by DataCreator index
   * This function gets data by index.
   */
  async getNutritionRecipeByDataCreator(
    data_creator: string,
  ): Promise<NutritionRecipeModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_recipe by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionRecipeByDataCreator(
    data_creator: string,
    data: NutritionRecipeModel
  ): Promise<NutritionRecipeModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = NutritionRecipeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_recipe by DataCreator index
   */
  async deleteNutritionRecipeByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get nutrition_recipe by DataUpdater index
   * This function gets data by index.
   */
  async getNutritionRecipeByDataUpdater(
    data_updater: string,
  ): Promise<NutritionRecipeModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_recipe by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionRecipeByDataUpdater(
    data_updater: string,
    data: NutritionRecipeModel
  ): Promise<NutritionRecipeModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = NutritionRecipeModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_recipe by DataUpdater index
   */
  async deleteNutritionRecipeByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to NutritionRecipeModel data array
   */
  private resultToData(values: Data[]): NutritionRecipeModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return NutritionRecipeModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as NutritionRecipeModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized NutritionRecipeModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is NutritionRecipeModel => item !== null);
  }
}

/**
 * Convert NutritionRecipeModel data to Value array
 */
function NutritionRecipeModelToValues(data: NutritionRecipeModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'meal_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'calories', type: DataType.number, defaultValue: 0 },
    { key: 'protein', type: DataType.number, defaultValue: 0 },
    { key: 'carbs', type: DataType.number, defaultValue: 0 },
    { key: 'fats', type: DataType.number, defaultValue: 0 },
    { key: 'ingredients', type: DataType.array, defaultValue: [] },
    { key: 'instructions', type: DataType.string, defaultValue: '' },
    { key: 'image_url', type: DataType.string, defaultValue: null },
    { key: 'prep_time_minutes', type: DataType.number, defaultValue: 0 },
    { key: 'is_premium', type: DataType.boolean, defaultValue: false },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof NutritionRecipeModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to NutritionRecipeModel data
 */
function NutritionRecipeModelFromValues(values: Value[]): NutritionRecipeModel {
  const data: Partial<NutritionRecipeModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'meal_type':
        data.meal_type = ParseValue(value, DataType.enumeration) as NutritionRecipeMealType;
        break;
      case 'calories':
        data.calories = ParseValue(value, DataType.number) as number;
        break;
      case 'protein':
        data.protein = ParseValue(value, DataType.number) as number;
        break;
      case 'carbs':
        data.carbs = ParseValue(value, DataType.number) as number;
        break;
      case 'fats':
        data.fats = ParseValue(value, DataType.number) as number;
        break;
      case 'ingredients':
        data.ingredients = ParseValue(value, DataType.array) as string[];
        break;
      case 'instructions':
        data.instructions = ParseValue(value, DataType.string) as string;
        break;
      case 'image_url':
        data.image_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'prep_time_minutes':
        data.prep_time_minutes = ParseValue(value, DataType.number) as number;
        break;
      case 'is_premium':
        data.is_premium = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as NutritionRecipeModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for MealType fields
 */
function createIndexMealType(
  meal_type: NutritionRecipeMealType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, meal_type, 'meal_type'),
  ];

  return {
    fields: ['meal_type'],
    values
  };
}
/**
 * Create index for IsPremium fields
 */
function createIndexIsPremium(
  is_premium: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_premium, 'is_premium'),
  ];

  return {
    fields: ['is_premium'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default NutritionRecipeORM;