// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: nutrition_log.
// - Entity ID: 102019ac25e7e4073a89cdad23d059d95d5.
// - Entity Version: 102019aca8871857d468edae750e17b27cf.
// - Task ID: 69299b9cbe7b168045cb8253.
// - Task Root ID: 6927837783045624aba5d052.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for NutritionLogMealType
 */
export enum NutritionLogMealType {
  Unspecified = 0,
  Breakfast = 1,
  Lunch = 2,
  Dinner = 3,
  Snack = 4,
}



/**
 * Interface for NutritionLogModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface NutritionLogModel {
  id: string;
  user_id: string;
  recipe_id: string;
  consumed_at: string;
  meal_type: NutritionLogMealType;
  calories: number;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for NutritionLog entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class NutritionLogORM {
  private static instance: NutritionLogORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac25e7e4073a89cdad23d059d95d5';
    this.entityName = 'nutrition_log';
    this.entityVersion = '102019aca8871857d468edae750e17b27cf';
    this.taskId = '69299b9cbe7b168045cb8253';
    this.taskRootId = '6927837783045624aba5d052';
  }

  /**
   * Get singleton instance of NutritionLogORM
   */
  public static getInstance(): NutritionLogORM {
    if (!NutritionLogORM.instance) {
      NutritionLogORM.instance = new NutritionLogORM();
    }
    
    return NutritionLogORM.instance;
  }

  /**
   * Get all NutritionLog records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllNutritionLog(): Promise<NutritionLogModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new NutritionLog record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertNutritionLog(data: NutritionLogModel[]): Promise<NutritionLogModel[]> {
    const structured = data.map((item) => CreateData(NutritionLogModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all NutritionLog records
   */
  async purgeAllNutritionLog(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List NutritionLog records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listNutritionLog(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[NutritionLogModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get nutrition_log by Id index
   * This function gets data by index.
   */
  async getNutritionLogById(
    id: string,
  ): Promise<NutritionLogModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_log by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionLogById(
    id: string,
    data: NutritionLogModel
  ): Promise<NutritionLogModel[]> {
    const index = createIndexId(
      id
    );

    const values = NutritionLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_log by Id index
   */
  async deleteNutritionLogById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get nutrition_log by UserId index
   * This function gets data by index.
   */
  async getNutritionLogByUserId(
    user_id: string,
  ): Promise<NutritionLogModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_log by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionLogByUserId(
    user_id: string,
    data: NutritionLogModel
  ): Promise<NutritionLogModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = NutritionLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_log by UserId index
   */
  async deleteNutritionLogByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get nutrition_log by RecipeId index
   * This function gets data by index.
   */
  async getNutritionLogByRecipeId(
    recipe_id: string,
  ): Promise<NutritionLogModel[]> {
    const index = createIndexRecipeId(
      recipe_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_log by RecipeId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionLogByRecipeId(
    recipe_id: string,
    data: NutritionLogModel
  ): Promise<NutritionLogModel[]> {
    const index = createIndexRecipeId(
      recipe_id
    );

    const values = NutritionLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_log by RecipeId index
   */
  async deleteNutritionLogByRecipeId(
    recipe_id: string
  ): Promise<void> {
    const index = createIndexRecipeId(
      recipe_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get nutrition_log by ConsumedAtUserId index
   * This function gets data by index.
   */
  async getNutritionLogByConsumedAtUserId(
    consumed_at: string,
    user_id: string,
  ): Promise<NutritionLogModel[]> {
    const index = createIndexConsumedAtUserId(
      consumed_at,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_log by ConsumedAtUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionLogByConsumedAtUserId(
    consumed_at: string,
    user_id: string,
    data: NutritionLogModel
  ): Promise<NutritionLogModel[]> {
    const index = createIndexConsumedAtUserId(
      consumed_at,
      user_id
    );

    const values = NutritionLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_log by ConsumedAtUserId index
   */
  async deleteNutritionLogByConsumedAtUserId(
    consumed_at: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexConsumedAtUserId(
      consumed_at,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get nutrition_log by DataCreator index
   * This function gets data by index.
   */
  async getNutritionLogByDataCreator(
    data_creator: string,
  ): Promise<NutritionLogModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_log by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionLogByDataCreator(
    data_creator: string,
    data: NutritionLogModel
  ): Promise<NutritionLogModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = NutritionLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_log by DataCreator index
   */
  async deleteNutritionLogByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get nutrition_log by DataUpdater index
   * This function gets data by index.
   */
  async getNutritionLogByDataUpdater(
    data_updater: string,
  ): Promise<NutritionLogModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) nutrition_log by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNutritionLogByDataUpdater(
    data_updater: string,
    data: NutritionLogModel
  ): Promise<NutritionLogModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = NutritionLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete nutrition_log by DataUpdater index
   */
  async deleteNutritionLogByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to NutritionLogModel data array
   */
  private resultToData(values: Data[]): NutritionLogModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return NutritionLogModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as NutritionLogModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized NutritionLogModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is NutritionLogModel => item !== null);
  }
}

/**
 * Convert NutritionLogModel data to Value array
 */
function NutritionLogModelToValues(data: NutritionLogModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'recipe_id', type: DataType.string, defaultValue: '' },
    { key: 'consumed_at', type: DataType.string, defaultValue: '' },
    { key: 'meal_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'calories', type: DataType.number, defaultValue: 0 },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof NutritionLogModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to NutritionLogModel data
 */
function NutritionLogModelFromValues(values: Value[]): NutritionLogModel {
  const data: Partial<NutritionLogModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'recipe_id':
        data.recipe_id = ParseValue(value, DataType.string) as string;
        break;
      case 'consumed_at':
        data.consumed_at = ParseValue(value, DataType.string) as string;
        break;
      case 'meal_type':
        data.meal_type = ParseValue(value, DataType.enumeration) as NutritionLogMealType;
        break;
      case 'calories':
        data.calories = ParseValue(value, DataType.number) as number;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as NutritionLogModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for RecipeId fields
 */
function createIndexRecipeId(
  recipe_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, recipe_id, 'recipe_id'),
  ];

  return {
    fields: ['recipe_id'],
    values
  };
}
/**
 * Create index for ConsumedAtUserId fields
 */
function createIndexConsumedAtUserId(
  consumed_at: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, consumed_at, 'consumed_at'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['consumed_at', 'user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default NutritionLogORM;