// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_profile.
// - Entity ID: 102019ac25e7e4077698af91d7354608d55.
// - Entity Version: 102019aca8871857d468edae750e17b27cf.
// - Task ID: 69299b9cbe7b168045cb8253.
// - Task Root ID: 6927837783045624aba5d052.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for UserProfileFitnessLevel
 */
export enum UserProfileFitnessLevel {
  Unspecified = 0,
  Beginner = 1,
  Intermediate = 2,
  Advanced = 3,
}
/**
 * Enumeration for UserProfileObjectivesItem
 */
export enum UserProfileObjectivesItem {
  Unspecified = 0,
  WeightLoss = 1,
  MuscleGain = 2,
  Toning = 3,
  Mobility = 4,
  HealthyLifestyle = 5,
}
/**
 * Enumeration for UserProfileSubscriptionTier
 */
export enum UserProfileSubscriptionTier {
  Unspecified = 0,
  Free = 1,
  Premium = 2,
}


/**
 * Interface for UserProfilePreferencesModel
 */
export interface UserProfilePreferencesModel {
  dark_mode: boolean;
  language: string;
  notifications_enabled: boolean;
}

/**
 * Interface for UserProfileModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserProfileModel {
  id: string;
  email: string;
  password: string;
  name: string;
  age?: number | null;
  weight?: number | null;
  height?: number | null;
  fitness_level?: UserProfileFitnessLevel | null;
  objectives?: any[] | null;
  subscription_tier: UserProfileSubscriptionTier;
  subscription_expiry_date?: string | null;
  preferences?: UserProfilePreferencesModel | null;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for UserProfile entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserProfileORM {
  private static instance: UserProfileORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac25e7e4077698af91d7354608d55';
    this.entityName = 'user_profile';
    this.entityVersion = '102019aca8871857d468edae750e17b27cf';
    this.taskId = '69299b9cbe7b168045cb8253';
    this.taskRootId = '6927837783045624aba5d052';
  }

  /**
   * Get singleton instance of UserProfileORM
   */
  public static getInstance(): UserProfileORM {
    if (!UserProfileORM.instance) {
      UserProfileORM.instance = new UserProfileORM();
    }
    
    return UserProfileORM.instance;
  }

  /**
   * Get all UserProfile records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserProfile(): Promise<UserProfileModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserProfile record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserProfile(data: UserProfileModel[]): Promise<UserProfileModel[]> {
    const structured = data.map((item) => CreateData(UserProfileModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserProfile records
   */
  async purgeAllUserProfile(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserProfile records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserProfile(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserProfileModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_profile by Id index
   * This function gets data by index.
   */
  async getUserProfileById(
    id: string,
  ): Promise<UserProfileModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileById(
    id: string,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by Id index
   */
  async deleteUserProfileById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_profile by Email index
   * This function gets data by index.
   */
  async getUserProfileByEmail(
    email: string,
  ): Promise<UserProfileModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileByEmail(
    email: string,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by Email index
   */
  async deleteUserProfileByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_profile by DataCreator index
   * This function gets data by index.
   */
  async getUserProfileByDataCreator(
    data_creator: string,
  ): Promise<UserProfileModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileByDataCreator(
    data_creator: string,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by DataCreator index
   */
  async deleteUserProfileByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_profile by DataUpdater index
   * This function gets data by index.
   */
  async getUserProfileByDataUpdater(
    data_updater: string,
  ): Promise<UserProfileModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileByDataUpdater(
    data_updater: string,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by DataUpdater index
   */
  async deleteUserProfileByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_profile by SubscriptionTier index
   * This function gets data by index.
   */
  async getUserProfileBySubscriptionTier(
    subscription_tier: UserProfileSubscriptionTier,
  ): Promise<UserProfileModel[]> {
    const index = createIndexSubscriptionTier(
      subscription_tier
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_profile by SubscriptionTier index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserProfileBySubscriptionTier(
    subscription_tier: UserProfileSubscriptionTier,
    data: UserProfileModel
  ): Promise<UserProfileModel[]> {
    const index = createIndexSubscriptionTier(
      subscription_tier
    );

    const values = UserProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_profile by SubscriptionTier index
   */
  async deleteUserProfileBySubscriptionTier(
    subscription_tier: UserProfileSubscriptionTier
  ): Promise<void> {
    const index = createIndexSubscriptionTier(
      subscription_tier
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserProfileModel data array
   */
  private resultToData(values: Data[]): UserProfileModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserProfileModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserProfileModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserProfileModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserProfileModel => item !== null);
  }
}

/**
 * Convert UserProfileModel data to Value array
 */
function UserProfileModelToValues(data: UserProfileModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'password', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'age', type: DataType.number, defaultValue: null },
    { key: 'weight', type: DataType.number, defaultValue: null },
    { key: 'height', type: DataType.number, defaultValue: null },
    { key: 'fitness_level', type: DataType.enumeration, defaultValue: null },
    { key: 'objectives', type: DataType.array, defaultValue: null },
    { key: 'subscription_tier', type: DataType.enumeration, defaultValue: 0 },
    { key: 'subscription_expiry_date', type: DataType.string, defaultValue: null },
    { key: 'preferences', type: DataType.object, defaultValue: null },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserProfileModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserProfileModel data
 */
function UserProfileModelFromValues(values: Value[]): UserProfileModel {
  const data: Partial<UserProfileModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'password':
        data.password = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'age':
        data.age = ParseValue(value, DataType.number) as number | null;
        break;
      case 'weight':
        data.weight = ParseValue(value, DataType.number) as number | null;
        break;
      case 'height':
        data.height = ParseValue(value, DataType.number) as number | null;
        break;
      case 'fitness_level':
        data.fitness_level = ParseValue(value, DataType.enumeration) as UserProfileFitnessLevel | null;
        break;
      case 'objectives':
        data.objectives = ParseValue(value, DataType.array) as any[] | null;
        break;
      case 'subscription_tier':
        data.subscription_tier = ParseValue(value, DataType.enumeration) as UserProfileSubscriptionTier;
        break;
      case 'subscription_expiry_date':
        data.subscription_expiry_date = ParseValue(value, DataType.string) as string | null;
        break;
      case 'preferences':
        data.preferences = ParseValue(value, DataType.object) as UserProfilePreferencesModel | null;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as UserProfileModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for SubscriptionTier fields
 */
function createIndexSubscriptionTier(
  subscription_tier: UserProfileSubscriptionTier
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, subscription_tier, 'subscription_tier'),
  ];

  return {
    fields: ['subscription_tier'],
    values
  };
}

export default UserProfileORM;