// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: workout.
// - Entity ID: 102019ac25e7e40798fb1c0635681923001.
// - Entity Version: 102019aca8871857d468edae750e17b27cf.
// - Task ID: 69299b9cbe7b168045cb8253.
// - Task Root ID: 6927837783045624aba5d052.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for WorkoutDifficultyLevel
 */
export enum WorkoutDifficultyLevel {
  Unspecified = 0,
  Beginner = 1,
  Intermediate = 2,
  Advanced = 3,
}



/**
 * Interface for WorkoutModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface WorkoutModel {
  id: string;
  workout_plan_id?: string | null;
  name: string;
  description?: string | null;
  category: string;
  difficulty_level: WorkoutDifficultyLevel;
  duration_minutes: number;
  video_url?: string | null;
  instructions: string;
  equipment_needed?: string[] | null;
  target_muscles?: string[] | null;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for Workout entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class WorkoutORM {
  private static instance: WorkoutORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac25e7e40798fb1c0635681923001';
    this.entityName = 'workout';
    this.entityVersion = '102019aca8871857d468edae750e17b27cf';
    this.taskId = '69299b9cbe7b168045cb8253';
    this.taskRootId = '6927837783045624aba5d052';
  }

  /**
   * Get singleton instance of WorkoutORM
   */
  public static getInstance(): WorkoutORM {
    if (!WorkoutORM.instance) {
      WorkoutORM.instance = new WorkoutORM();
    }
    
    return WorkoutORM.instance;
  }

  /**
   * Get all Workout records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllWorkout(): Promise<WorkoutModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Workout record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertWorkout(data: WorkoutModel[]): Promise<WorkoutModel[]> {
    const structured = data.map((item) => CreateData(WorkoutModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Workout records
   */
  async purgeAllWorkout(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Workout records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listWorkout(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[WorkoutModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get workout by Id index
   * This function gets data by index.
   */
  async getWorkoutById(
    id: string,
  ): Promise<WorkoutModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutById(
    id: string,
    data: WorkoutModel
  ): Promise<WorkoutModel[]> {
    const index = createIndexId(
      id
    );

    const values = WorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout by Id index
   */
  async deleteWorkoutById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get workout by WorkoutPlanId index
   * This function gets data by index.
   */
  async getWorkoutByWorkoutPlanId(
    workout_plan_id: string,
  ): Promise<WorkoutModel[]> {
    const index = createIndexWorkoutPlanId(
      workout_plan_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout by WorkoutPlanId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutByWorkoutPlanId(
    workout_plan_id: string,
    data: WorkoutModel
  ): Promise<WorkoutModel[]> {
    const index = createIndexWorkoutPlanId(
      workout_plan_id
    );

    const values = WorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout by WorkoutPlanId index
   */
  async deleteWorkoutByWorkoutPlanId(
    workout_plan_id: string
  ): Promise<void> {
    const index = createIndexWorkoutPlanId(
      workout_plan_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get workout by Category index
   * This function gets data by index.
   */
  async getWorkoutByCategory(
    category: string,
  ): Promise<WorkoutModel[]> {
    const index = createIndexCategory(
      category
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout by Category index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutByCategory(
    category: string,
    data: WorkoutModel
  ): Promise<WorkoutModel[]> {
    const index = createIndexCategory(
      category
    );

    const values = WorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout by Category index
   */
  async deleteWorkoutByCategory(
    category: string
  ): Promise<void> {
    const index = createIndexCategory(
      category
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get workout by DifficultyLevel index
   * This function gets data by index.
   */
  async getWorkoutByDifficultyLevel(
    difficulty_level: WorkoutDifficultyLevel,
  ): Promise<WorkoutModel[]> {
    const index = createIndexDifficultyLevel(
      difficulty_level
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout by DifficultyLevel index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutByDifficultyLevel(
    difficulty_level: WorkoutDifficultyLevel,
    data: WorkoutModel
  ): Promise<WorkoutModel[]> {
    const index = createIndexDifficultyLevel(
      difficulty_level
    );

    const values = WorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout by DifficultyLevel index
   */
  async deleteWorkoutByDifficultyLevel(
    difficulty_level: WorkoutDifficultyLevel
  ): Promise<void> {
    const index = createIndexDifficultyLevel(
      difficulty_level
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get workout by DataCreator index
   * This function gets data by index.
   */
  async getWorkoutByDataCreator(
    data_creator: string,
  ): Promise<WorkoutModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutByDataCreator(
    data_creator: string,
    data: WorkoutModel
  ): Promise<WorkoutModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = WorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout by DataCreator index
   */
  async deleteWorkoutByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get workout by DataUpdater index
   * This function gets data by index.
   */
  async getWorkoutByDataUpdater(
    data_updater: string,
  ): Promise<WorkoutModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutByDataUpdater(
    data_updater: string,
    data: WorkoutModel
  ): Promise<WorkoutModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = WorkoutModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout by DataUpdater index
   */
  async deleteWorkoutByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to WorkoutModel data array
   */
  private resultToData(values: Data[]): WorkoutModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return WorkoutModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as WorkoutModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized WorkoutModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is WorkoutModel => item !== null);
  }
}

/**
 * Convert WorkoutModel data to Value array
 */
function WorkoutModelToValues(data: WorkoutModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'workout_plan_id', type: DataType.string, defaultValue: null },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'category', type: DataType.string, defaultValue: '' },
    { key: 'difficulty_level', type: DataType.enumeration, defaultValue: 0 },
    { key: 'duration_minutes', type: DataType.number, defaultValue: 0 },
    { key: 'video_url', type: DataType.string, defaultValue: null },
    { key: 'instructions', type: DataType.string, defaultValue: '' },
    { key: 'equipment_needed', type: DataType.array, defaultValue: null },
    { key: 'target_muscles', type: DataType.array, defaultValue: null },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof WorkoutModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to WorkoutModel data
 */
function WorkoutModelFromValues(values: Value[]): WorkoutModel {
  const data: Partial<WorkoutModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'workout_plan_id':
        data.workout_plan_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.string) as string;
        break;
      case 'difficulty_level':
        data.difficulty_level = ParseValue(value, DataType.enumeration) as WorkoutDifficultyLevel;
        break;
      case 'duration_minutes':
        data.duration_minutes = ParseValue(value, DataType.number) as number;
        break;
      case 'video_url':
        data.video_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'instructions':
        data.instructions = ParseValue(value, DataType.string) as string;
        break;
      case 'equipment_needed':
        data.equipment_needed = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'target_muscles':
        data.target_muscles = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as WorkoutModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for WorkoutPlanId fields
 */
function createIndexWorkoutPlanId(
  workout_plan_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, workout_plan_id, 'workout_plan_id'),
  ];

  return {
    fields: ['workout_plan_id'],
    values
  };
}
/**
 * Create index for Category fields
 */
function createIndexCategory(
  category: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, category, 'category'),
  ];

  return {
    fields: ['category'],
    values
  };
}
/**
 * Create index for DifficultyLevel fields
 */
function createIndexDifficultyLevel(
  difficulty_level: WorkoutDifficultyLevel
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, difficulty_level, 'difficulty_level'),
  ];

  return {
    fields: ['difficulty_level'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default WorkoutORM;