// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: exercise_log.
// - Entity ID: 102019ac25e7e3f7ac3b10b11477d36fa77.
// - Entity Version: 102019aca8871857d468edae750e17b27cf.
// - Task ID: 69299b9cbe7b168045cb8253.
// - Task Root ID: 6927837783045624aba5d052.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for ExerciseLogModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ExerciseLogModel {
  id: string;
  user_id: string;
  workout_id: string;
  completed_at: string;
  duration_minutes: number;
  calories_burned?: number | null;
  notes?: string | null;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for ExerciseLog entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ExerciseLogORM {
  private static instance: ExerciseLogORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac25e7e3f7ac3b10b11477d36fa77';
    this.entityName = 'exercise_log';
    this.entityVersion = '102019aca8871857d468edae750e17b27cf';
    this.taskId = '69299b9cbe7b168045cb8253';
    this.taskRootId = '6927837783045624aba5d052';
  }

  /**
   * Get singleton instance of ExerciseLogORM
   */
  public static getInstance(): ExerciseLogORM {
    if (!ExerciseLogORM.instance) {
      ExerciseLogORM.instance = new ExerciseLogORM();
    }
    
    return ExerciseLogORM.instance;
  }

  /**
   * Get all ExerciseLog records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllExerciseLog(): Promise<ExerciseLogModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ExerciseLog record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertExerciseLog(data: ExerciseLogModel[]): Promise<ExerciseLogModel[]> {
    const structured = data.map((item) => CreateData(ExerciseLogModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ExerciseLog records
   */
  async purgeAllExerciseLog(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ExerciseLog records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listExerciseLog(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ExerciseLogModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get exercise_log by Id index
   * This function gets data by index.
   */
  async getExerciseLogById(
    id: string,
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exercise_log by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExerciseLogById(
    id: string,
    data: ExerciseLogModel
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexId(
      id
    );

    const values = ExerciseLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exercise_log by Id index
   */
  async deleteExerciseLogById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exercise_log by UserId index
   * This function gets data by index.
   */
  async getExerciseLogByUserId(
    user_id: string,
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exercise_log by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExerciseLogByUserId(
    user_id: string,
    data: ExerciseLogModel
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = ExerciseLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exercise_log by UserId index
   */
  async deleteExerciseLogByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exercise_log by WorkoutId index
   * This function gets data by index.
   */
  async getExerciseLogByWorkoutId(
    workout_id: string,
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexWorkoutId(
      workout_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exercise_log by WorkoutId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExerciseLogByWorkoutId(
    workout_id: string,
    data: ExerciseLogModel
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexWorkoutId(
      workout_id
    );

    const values = ExerciseLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exercise_log by WorkoutId index
   */
  async deleteExerciseLogByWorkoutId(
    workout_id: string
  ): Promise<void> {
    const index = createIndexWorkoutId(
      workout_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exercise_log by CompletedAtUserId index
   * This function gets data by index.
   */
  async getExerciseLogByCompletedAtUserId(
    completed_at: string,
    user_id: string,
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexCompletedAtUserId(
      completed_at,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exercise_log by CompletedAtUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExerciseLogByCompletedAtUserId(
    completed_at: string,
    user_id: string,
    data: ExerciseLogModel
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexCompletedAtUserId(
      completed_at,
      user_id
    );

    const values = ExerciseLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exercise_log by CompletedAtUserId index
   */
  async deleteExerciseLogByCompletedAtUserId(
    completed_at: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexCompletedAtUserId(
      completed_at,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exercise_log by DataCreator index
   * This function gets data by index.
   */
  async getExerciseLogByDataCreator(
    data_creator: string,
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exercise_log by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExerciseLogByDataCreator(
    data_creator: string,
    data: ExerciseLogModel
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ExerciseLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exercise_log by DataCreator index
   */
  async deleteExerciseLogByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get exercise_log by DataUpdater index
   * This function gets data by index.
   */
  async getExerciseLogByDataUpdater(
    data_updater: string,
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) exercise_log by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setExerciseLogByDataUpdater(
    data_updater: string,
    data: ExerciseLogModel
  ): Promise<ExerciseLogModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ExerciseLogModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete exercise_log by DataUpdater index
   */
  async deleteExerciseLogByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ExerciseLogModel data array
   */
  private resultToData(values: Data[]): ExerciseLogModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ExerciseLogModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ExerciseLogModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ExerciseLogModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ExerciseLogModel => item !== null);
  }
}

/**
 * Convert ExerciseLogModel data to Value array
 */
function ExerciseLogModelToValues(data: ExerciseLogModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'workout_id', type: DataType.string, defaultValue: '' },
    { key: 'completed_at', type: DataType.string, defaultValue: '' },
    { key: 'duration_minutes', type: DataType.number, defaultValue: 0 },
    { key: 'calories_burned', type: DataType.number, defaultValue: null },
    { key: 'notes', type: DataType.string, defaultValue: null },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ExerciseLogModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ExerciseLogModel data
 */
function ExerciseLogModelFromValues(values: Value[]): ExerciseLogModel {
  const data: Partial<ExerciseLogModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'workout_id':
        data.workout_id = ParseValue(value, DataType.string) as string;
        break;
      case 'completed_at':
        data.completed_at = ParseValue(value, DataType.string) as string;
        break;
      case 'duration_minutes':
        data.duration_minutes = ParseValue(value, DataType.number) as number;
        break;
      case 'calories_burned':
        data.calories_burned = ParseValue(value, DataType.number) as number | null;
        break;
      case 'notes':
        data.notes = ParseValue(value, DataType.string) as string | null;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ExerciseLogModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for WorkoutId fields
 */
function createIndexWorkoutId(
  workout_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, workout_id, 'workout_id'),
  ];

  return {
    fields: ['workout_id'],
    values
  };
}
/**
 * Create index for CompletedAtUserId fields
 */
function createIndexCompletedAtUserId(
  completed_at: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, completed_at, 'completed_at'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['completed_at', 'user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ExerciseLogORM;