// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: progress_metric.
// - Entity ID: 102019ac25e7e4074ff8b00137ecd24bc4f.
// - Entity Version: 102019aca8871857d468edae750e17b27cf.
// - Task ID: 69299b9cbe7b168045cb8253.
// - Task Root ID: 6927837783045624aba5d052.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for ProgressMetricModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ProgressMetricModel {
  id: string;
  user_id: string;
  date: string;
  weight: number;
  body_fat_percentage?: number | null;
  notes?: string | null;
  measurements?: string | null;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for ProgressMetric entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ProgressMetricORM {
  private static instance: ProgressMetricORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac25e7e4074ff8b00137ecd24bc4f';
    this.entityName = 'progress_metric';
    this.entityVersion = '102019aca8871857d468edae750e17b27cf';
    this.taskId = '69299b9cbe7b168045cb8253';
    this.taskRootId = '6927837783045624aba5d052';
  }

  /**
   * Get singleton instance of ProgressMetricORM
   */
  public static getInstance(): ProgressMetricORM {
    if (!ProgressMetricORM.instance) {
      ProgressMetricORM.instance = new ProgressMetricORM();
    }
    
    return ProgressMetricORM.instance;
  }

  /**
   * Get all ProgressMetric records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllProgressMetric(): Promise<ProgressMetricModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ProgressMetric record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertProgressMetric(data: ProgressMetricModel[]): Promise<ProgressMetricModel[]> {
    const structured = data.map((item) => CreateData(ProgressMetricModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ProgressMetric records
   */
  async purgeAllProgressMetric(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ProgressMetric records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listProgressMetric(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ProgressMetricModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get progress_metric by Id index
   * This function gets data by index.
   */
  async getProgressMetricById(
    id: string,
  ): Promise<ProgressMetricModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) progress_metric by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgressMetricById(
    id: string,
    data: ProgressMetricModel
  ): Promise<ProgressMetricModel[]> {
    const index = createIndexId(
      id
    );

    const values = ProgressMetricModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete progress_metric by Id index
   */
  async deleteProgressMetricById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get progress_metric by UserId index
   * This function gets data by index.
   */
  async getProgressMetricByUserId(
    user_id: string,
  ): Promise<ProgressMetricModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) progress_metric by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgressMetricByUserId(
    user_id: string,
    data: ProgressMetricModel
  ): Promise<ProgressMetricModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = ProgressMetricModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete progress_metric by UserId index
   */
  async deleteProgressMetricByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get progress_metric by DateUserId index
   * This function gets data by index.
   */
  async getProgressMetricByDateUserId(
    date: string,
    user_id: string,
  ): Promise<ProgressMetricModel[]> {
    const index = createIndexDateUserId(
      date,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) progress_metric by DateUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgressMetricByDateUserId(
    date: string,
    user_id: string,
    data: ProgressMetricModel
  ): Promise<ProgressMetricModel[]> {
    const index = createIndexDateUserId(
      date,
      user_id
    );

    const values = ProgressMetricModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete progress_metric by DateUserId index
   */
  async deleteProgressMetricByDateUserId(
    date: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexDateUserId(
      date,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get progress_metric by DataCreator index
   * This function gets data by index.
   */
  async getProgressMetricByDataCreator(
    data_creator: string,
  ): Promise<ProgressMetricModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) progress_metric by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgressMetricByDataCreator(
    data_creator: string,
    data: ProgressMetricModel
  ): Promise<ProgressMetricModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ProgressMetricModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete progress_metric by DataCreator index
   */
  async deleteProgressMetricByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get progress_metric by DataUpdater index
   * This function gets data by index.
   */
  async getProgressMetricByDataUpdater(
    data_updater: string,
  ): Promise<ProgressMetricModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) progress_metric by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setProgressMetricByDataUpdater(
    data_updater: string,
    data: ProgressMetricModel
  ): Promise<ProgressMetricModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ProgressMetricModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete progress_metric by DataUpdater index
   */
  async deleteProgressMetricByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ProgressMetricModel data array
   */
  private resultToData(values: Data[]): ProgressMetricModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ProgressMetricModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ProgressMetricModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ProgressMetricModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ProgressMetricModel => item !== null);
  }
}

/**
 * Convert ProgressMetricModel data to Value array
 */
function ProgressMetricModelToValues(data: ProgressMetricModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'date', type: DataType.string, defaultValue: '' },
    { key: 'weight', type: DataType.number, defaultValue: 0 },
    { key: 'body_fat_percentage', type: DataType.number, defaultValue: null },
    { key: 'notes', type: DataType.string, defaultValue: null },
    { key: 'measurements', type: DataType.string, defaultValue: null },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ProgressMetricModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ProgressMetricModel data
 */
function ProgressMetricModelFromValues(values: Value[]): ProgressMetricModel {
  const data: Partial<ProgressMetricModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'date':
        data.date = ParseValue(value, DataType.string) as string;
        break;
      case 'weight':
        data.weight = ParseValue(value, DataType.number) as number;
        break;
      case 'body_fat_percentage':
        data.body_fat_percentage = ParseValue(value, DataType.number) as number | null;
        break;
      case 'notes':
        data.notes = ParseValue(value, DataType.string) as string | null;
        break;
      case 'measurements':
        data.measurements = ParseValue(value, DataType.string) as string | null;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ProgressMetricModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DateUserId fields
 */
function createIndexDateUserId(
  date: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, date, 'date'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['date', 'user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ProgressMetricORM;