// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_favorite.
// - Entity ID: 102019ac25e7e407647adc0373483d4140c.
// - Entity Version: 102019aca8871857d468edae750e17b27cf.
// - Task ID: 69299b9cbe7b168045cb8253.
// - Task Root ID: 6927837783045624aba5d052.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for UserFavoriteItemType
 */
export enum UserFavoriteItemType {
  Unspecified = 0,
  Workout = 1,
  Recipe = 2,
  Content = 3,
}



/**
 * Interface for UserFavoriteModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserFavoriteModel {
  id: string;
  user_id: string;
  item_id: string;
  item_type: UserFavoriteItemType;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for UserFavorite entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserFavoriteORM {
  private static instance: UserFavoriteORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac25e7e407647adc0373483d4140c';
    this.entityName = 'user_favorite';
    this.entityVersion = '102019aca8871857d468edae750e17b27cf';
    this.taskId = '69299b9cbe7b168045cb8253';
    this.taskRootId = '6927837783045624aba5d052';
  }

  /**
   * Get singleton instance of UserFavoriteORM
   */
  public static getInstance(): UserFavoriteORM {
    if (!UserFavoriteORM.instance) {
      UserFavoriteORM.instance = new UserFavoriteORM();
    }
    
    return UserFavoriteORM.instance;
  }

  /**
   * Get all UserFavorite records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserFavorite(): Promise<UserFavoriteModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserFavorite record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserFavorite(data: UserFavoriteModel[]): Promise<UserFavoriteModel[]> {
    const structured = data.map((item) => CreateData(UserFavoriteModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserFavorite records
   */
  async purgeAllUserFavorite(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserFavorite records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserFavorite(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserFavoriteModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_favorite by Id index
   * This function gets data by index.
   */
  async getUserFavoriteById(
    id: string,
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_favorite by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFavoriteById(
    id: string,
    data: UserFavoriteModel
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserFavoriteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_favorite by Id index
   */
  async deleteUserFavoriteById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_favorite by UserId index
   * This function gets data by index.
   */
  async getUserFavoriteByUserId(
    user_id: string,
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_favorite by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFavoriteByUserId(
    user_id: string,
    data: UserFavoriteModel
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = UserFavoriteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_favorite by UserId index
   */
  async deleteUserFavoriteByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_favorite by ItemTypeUserId index
   * This function gets data by index.
   */
  async getUserFavoriteByItemTypeUserId(
    item_type: UserFavoriteItemType,
    user_id: string,
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexItemTypeUserId(
      item_type,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_favorite by ItemTypeUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFavoriteByItemTypeUserId(
    item_type: UserFavoriteItemType,
    user_id: string,
    data: UserFavoriteModel
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexItemTypeUserId(
      item_type,
      user_id
    );

    const values = UserFavoriteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_favorite by ItemTypeUserId index
   */
  async deleteUserFavoriteByItemTypeUserId(
    item_type: UserFavoriteItemType,
    user_id: string
  ): Promise<void> {
    const index = createIndexItemTypeUserId(
      item_type,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_favorite by ItemIdItemTypeUserId index
   * This function gets data by index.
   */
  async getUserFavoriteByItemIdItemTypeUserId(
    item_id: string,
    item_type: UserFavoriteItemType,
    user_id: string,
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexItemIdItemTypeUserId(
      item_id,
      item_type,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_favorite by ItemIdItemTypeUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFavoriteByItemIdItemTypeUserId(
    item_id: string,
    item_type: UserFavoriteItemType,
    user_id: string,
    data: UserFavoriteModel
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexItemIdItemTypeUserId(
      item_id,
      item_type,
      user_id
    );

    const values = UserFavoriteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_favorite by ItemIdItemTypeUserId index
   */
  async deleteUserFavoriteByItemIdItemTypeUserId(
    item_id: string,
    item_type: UserFavoriteItemType,
    user_id: string
  ): Promise<void> {
    const index = createIndexItemIdItemTypeUserId(
      item_id,
      item_type,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_favorite by DataCreator index
   * This function gets data by index.
   */
  async getUserFavoriteByDataCreator(
    data_creator: string,
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_favorite by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFavoriteByDataCreator(
    data_creator: string,
    data: UserFavoriteModel
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserFavoriteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_favorite by DataCreator index
   */
  async deleteUserFavoriteByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_favorite by DataUpdater index
   * This function gets data by index.
   */
  async getUserFavoriteByDataUpdater(
    data_updater: string,
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_favorite by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserFavoriteByDataUpdater(
    data_updater: string,
    data: UserFavoriteModel
  ): Promise<UserFavoriteModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserFavoriteModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_favorite by DataUpdater index
   */
  async deleteUserFavoriteByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserFavoriteModel data array
   */
  private resultToData(values: Data[]): UserFavoriteModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserFavoriteModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserFavoriteModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserFavoriteModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserFavoriteModel => item !== null);
  }
}

/**
 * Convert UserFavoriteModel data to Value array
 */
function UserFavoriteModelToValues(data: UserFavoriteModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'item_id', type: DataType.string, defaultValue: '' },
    { key: 'item_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserFavoriteModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserFavoriteModel data
 */
function UserFavoriteModelFromValues(values: Value[]): UserFavoriteModel {
  const data: Partial<UserFavoriteModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'item_id':
        data.item_id = ParseValue(value, DataType.string) as string;
        break;
      case 'item_type':
        data.item_type = ParseValue(value, DataType.enumeration) as UserFavoriteItemType;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as UserFavoriteModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for ItemTypeUserId fields
 */
function createIndexItemTypeUserId(
  item_type: UserFavoriteItemType,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, item_type, 'item_type'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['item_type', 'user_id'],
    values
  };
}
/**
 * Create index for ItemIdItemTypeUserId fields
 */
function createIndexItemIdItemTypeUserId(
  item_id: string,
  item_type: UserFavoriteItemType,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, item_id, 'item_id'),
    CreateValue(DataType.enumeration, item_type, 'item_type'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['item_id', 'item_type', 'user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default UserFavoriteORM;