// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: workout_plan.
// - Entity ID: 102019ac25e7e40702395ef76e2fb13ad9c.
// - Entity Version: 102019aca8871857d468edae750e17b27cf.
// - Task ID: 69299b9cbe7b168045cb8253.
// - Task Root ID: 6927837783045624aba5d052.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for WorkoutPlanDifficultyLevel
 */
export enum WorkoutPlanDifficultyLevel {
  Unspecified = 0,
  Beginner = 1,
  Intermediate = 2,
  Advanced = 3,
}
/**
 * Enumeration for WorkoutPlanObjectivesItem
 */
export enum WorkoutPlanObjectivesItem {
  Unspecified = 0,
  WeightLoss = 1,
  MuscleGain = 2,
  Toning = 3,
  Mobility = 4,
  HealthyLifestyle = 5,
}



/**
 * Interface for WorkoutPlanModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface WorkoutPlanModel {
  id: string;
  user_id: string;
  name: string;
  description?: string | null;
  difficulty_level: WorkoutPlanDifficultyLevel;
  objectives?: any[] | null;
  duration_weeks: number;
  ai_generated: boolean;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for WorkoutPlan entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class WorkoutPlanORM {
  private static instance: WorkoutPlanORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac25e7e40702395ef76e2fb13ad9c';
    this.entityName = 'workout_plan';
    this.entityVersion = '102019aca8871857d468edae750e17b27cf';
    this.taskId = '69299b9cbe7b168045cb8253';
    this.taskRootId = '6927837783045624aba5d052';
  }

  /**
   * Get singleton instance of WorkoutPlanORM
   */
  public static getInstance(): WorkoutPlanORM {
    if (!WorkoutPlanORM.instance) {
      WorkoutPlanORM.instance = new WorkoutPlanORM();
    }
    
    return WorkoutPlanORM.instance;
  }

  /**
   * Get all WorkoutPlan records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllWorkoutPlan(): Promise<WorkoutPlanModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new WorkoutPlan record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertWorkoutPlan(data: WorkoutPlanModel[]): Promise<WorkoutPlanModel[]> {
    const structured = data.map((item) => CreateData(WorkoutPlanModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all WorkoutPlan records
   */
  async purgeAllWorkoutPlan(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List WorkoutPlan records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listWorkoutPlan(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[WorkoutPlanModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get workout_plan by Id index
   * This function gets data by index.
   */
  async getWorkoutPlanById(
    id: string,
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout_plan by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutPlanById(
    id: string,
    data: WorkoutPlanModel
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexId(
      id
    );

    const values = WorkoutPlanModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout_plan by Id index
   */
  async deleteWorkoutPlanById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get workout_plan by UserId index
   * This function gets data by index.
   */
  async getWorkoutPlanByUserId(
    user_id: string,
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout_plan by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutPlanByUserId(
    user_id: string,
    data: WorkoutPlanModel
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = WorkoutPlanModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout_plan by UserId index
   */
  async deleteWorkoutPlanByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get workout_plan by DifficultyLevel index
   * This function gets data by index.
   */
  async getWorkoutPlanByDifficultyLevel(
    difficulty_level: WorkoutPlanDifficultyLevel,
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexDifficultyLevel(
      difficulty_level
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout_plan by DifficultyLevel index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutPlanByDifficultyLevel(
    difficulty_level: WorkoutPlanDifficultyLevel,
    data: WorkoutPlanModel
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexDifficultyLevel(
      difficulty_level
    );

    const values = WorkoutPlanModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout_plan by DifficultyLevel index
   */
  async deleteWorkoutPlanByDifficultyLevel(
    difficulty_level: WorkoutPlanDifficultyLevel
  ): Promise<void> {
    const index = createIndexDifficultyLevel(
      difficulty_level
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get workout_plan by AiGenerated index
   * This function gets data by index.
   */
  async getWorkoutPlanByAiGenerated(
    ai_generated: boolean,
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexAiGenerated(
      ai_generated
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout_plan by AiGenerated index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutPlanByAiGenerated(
    ai_generated: boolean,
    data: WorkoutPlanModel
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexAiGenerated(
      ai_generated
    );

    const values = WorkoutPlanModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout_plan by AiGenerated index
   */
  async deleteWorkoutPlanByAiGenerated(
    ai_generated: boolean
  ): Promise<void> {
    const index = createIndexAiGenerated(
      ai_generated
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get workout_plan by DataCreator index
   * This function gets data by index.
   */
  async getWorkoutPlanByDataCreator(
    data_creator: string,
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout_plan by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutPlanByDataCreator(
    data_creator: string,
    data: WorkoutPlanModel
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = WorkoutPlanModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout_plan by DataCreator index
   */
  async deleteWorkoutPlanByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get workout_plan by DataUpdater index
   * This function gets data by index.
   */
  async getWorkoutPlanByDataUpdater(
    data_updater: string,
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) workout_plan by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkoutPlanByDataUpdater(
    data_updater: string,
    data: WorkoutPlanModel
  ): Promise<WorkoutPlanModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = WorkoutPlanModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete workout_plan by DataUpdater index
   */
  async deleteWorkoutPlanByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to WorkoutPlanModel data array
   */
  private resultToData(values: Data[]): WorkoutPlanModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return WorkoutPlanModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as WorkoutPlanModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized WorkoutPlanModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is WorkoutPlanModel => item !== null);
  }
}

/**
 * Convert WorkoutPlanModel data to Value array
 */
function WorkoutPlanModelToValues(data: WorkoutPlanModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'difficulty_level', type: DataType.enumeration, defaultValue: 0 },
    { key: 'objectives', type: DataType.array, defaultValue: null },
    { key: 'duration_weeks', type: DataType.number, defaultValue: 0 },
    { key: 'ai_generated', type: DataType.boolean, defaultValue: false },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof WorkoutPlanModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to WorkoutPlanModel data
 */
function WorkoutPlanModelFromValues(values: Value[]): WorkoutPlanModel {
  const data: Partial<WorkoutPlanModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'difficulty_level':
        data.difficulty_level = ParseValue(value, DataType.enumeration) as WorkoutPlanDifficultyLevel;
        break;
      case 'objectives':
        data.objectives = ParseValue(value, DataType.array) as any[] | null;
        break;
      case 'duration_weeks':
        data.duration_weeks = ParseValue(value, DataType.number) as number;
        break;
      case 'ai_generated':
        data.ai_generated = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as WorkoutPlanModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DifficultyLevel fields
 */
function createIndexDifficultyLevel(
  difficulty_level: WorkoutPlanDifficultyLevel
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, difficulty_level, 'difficulty_level'),
  ];

  return {
    fields: ['difficulty_level'],
    values
  };
}
/**
 * Create index for AiGenerated fields
 */
function createIndexAiGenerated(
  ai_generated: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, ai_generated, 'ai_generated'),
  ];

  return {
    fields: ['ai_generated'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default WorkoutPlanORM;