// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: lifestyle_content.
// - Entity ID: 102019ac25e7e3f7da88435d48a37bf37cf.
// - Entity Version: 102019aca8871857d468edae750e17b27cf.
// - Task ID: 69299b9cbe7b168045cb8253.
// - Task Root ID: 6927837783045624aba5d052.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for LifestyleContentContentType
 */
export enum LifestyleContentContentType {
  Unspecified = 0,
  Article = 1,
  Video = 2,
}



/**
 * Interface for LifestyleContentModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface LifestyleContentModel {
  id: string;
  title: string;
  content: string;
  category: string;
  content_type: LifestyleContentContentType;
  is_premium: boolean;
  image_url?: string | null;
  video_url?: string | null;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
}

/**
 * ORM class for LifestyleContent entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class LifestyleContentORM {
  private static instance: LifestyleContentORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ac25e7e3f7da88435d48a37bf37cf';
    this.entityName = 'lifestyle_content';
    this.entityVersion = '102019aca8871857d468edae750e17b27cf';
    this.taskId = '69299b9cbe7b168045cb8253';
    this.taskRootId = '6927837783045624aba5d052';
  }

  /**
   * Get singleton instance of LifestyleContentORM
   */
  public static getInstance(): LifestyleContentORM {
    if (!LifestyleContentORM.instance) {
      LifestyleContentORM.instance = new LifestyleContentORM();
    }
    
    return LifestyleContentORM.instance;
  }

  /**
   * Get all LifestyleContent records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllLifestyleContent(): Promise<LifestyleContentModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new LifestyleContent record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertLifestyleContent(data: LifestyleContentModel[]): Promise<LifestyleContentModel[]> {
    const structured = data.map((item) => CreateData(LifestyleContentModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all LifestyleContent records
   */
  async purgeAllLifestyleContent(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List LifestyleContent records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listLifestyleContent(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[LifestyleContentModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get lifestyle_content by Id index
   * This function gets data by index.
   */
  async getLifestyleContentById(
    id: string,
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lifestyle_content by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLifestyleContentById(
    id: string,
    data: LifestyleContentModel
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexId(
      id
    );

    const values = LifestyleContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lifestyle_content by Id index
   */
  async deleteLifestyleContentById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get lifestyle_content by Category index
   * This function gets data by index.
   */
  async getLifestyleContentByCategory(
    category: string,
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexCategory(
      category
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lifestyle_content by Category index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLifestyleContentByCategory(
    category: string,
    data: LifestyleContentModel
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexCategory(
      category
    );

    const values = LifestyleContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lifestyle_content by Category index
   */
  async deleteLifestyleContentByCategory(
    category: string
  ): Promise<void> {
    const index = createIndexCategory(
      category
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get lifestyle_content by ContentType index
   * This function gets data by index.
   */
  async getLifestyleContentByContentType(
    content_type: LifestyleContentContentType,
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexContentType(
      content_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lifestyle_content by ContentType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLifestyleContentByContentType(
    content_type: LifestyleContentContentType,
    data: LifestyleContentModel
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexContentType(
      content_type
    );

    const values = LifestyleContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lifestyle_content by ContentType index
   */
  async deleteLifestyleContentByContentType(
    content_type: LifestyleContentContentType
  ): Promise<void> {
    const index = createIndexContentType(
      content_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get lifestyle_content by IsPremium index
   * This function gets data by index.
   */
  async getLifestyleContentByIsPremium(
    is_premium: boolean,
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexIsPremium(
      is_premium
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lifestyle_content by IsPremium index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLifestyleContentByIsPremium(
    is_premium: boolean,
    data: LifestyleContentModel
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexIsPremium(
      is_premium
    );

    const values = LifestyleContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lifestyle_content by IsPremium index
   */
  async deleteLifestyleContentByIsPremium(
    is_premium: boolean
  ): Promise<void> {
    const index = createIndexIsPremium(
      is_premium
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get lifestyle_content by DataCreator index
   * This function gets data by index.
   */
  async getLifestyleContentByDataCreator(
    data_creator: string,
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lifestyle_content by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLifestyleContentByDataCreator(
    data_creator: string,
    data: LifestyleContentModel
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = LifestyleContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lifestyle_content by DataCreator index
   */
  async deleteLifestyleContentByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get lifestyle_content by DataUpdater index
   * This function gets data by index.
   */
  async getLifestyleContentByDataUpdater(
    data_updater: string,
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) lifestyle_content by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setLifestyleContentByDataUpdater(
    data_updater: string,
    data: LifestyleContentModel
  ): Promise<LifestyleContentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = LifestyleContentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete lifestyle_content by DataUpdater index
   */
  async deleteLifestyleContentByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to LifestyleContentModel data array
   */
  private resultToData(values: Data[]): LifestyleContentModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return LifestyleContentModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as LifestyleContentModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized LifestyleContentModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is LifestyleContentModel => item !== null);
  }
}

/**
 * Convert LifestyleContentModel data to Value array
 */
function LifestyleContentModelToValues(data: LifestyleContentModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'content', type: DataType.string, defaultValue: '' },
    { key: 'category', type: DataType.string, defaultValue: '' },
    { key: 'content_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'is_premium', type: DataType.boolean, defaultValue: false },
    { key: 'image_url', type: DataType.string, defaultValue: null },
    { key: 'video_url', type: DataType.string, defaultValue: null },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof LifestyleContentModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to LifestyleContentModel data
 */
function LifestyleContentModelFromValues(values: Value[]): LifestyleContentModel {
  const data: Partial<LifestyleContentModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'content':
        data.content = ParseValue(value, DataType.string) as string;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.string) as string;
        break;
      case 'content_type':
        data.content_type = ParseValue(value, DataType.enumeration) as LifestyleContentContentType;
        break;
      case 'is_premium':
        data.is_premium = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'image_url':
        data.image_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'video_url':
        data.video_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as LifestyleContentModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Category fields
 */
function createIndexCategory(
  category: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, category, 'category'),
  ];

  return {
    fields: ['category'],
    values
  };
}
/**
 * Create index for ContentType fields
 */
function createIndexContentType(
  content_type: LifestyleContentContentType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, content_type, 'content_type'),
  ];

  return {
    fields: ['content_type'],
    values
  };
}
/**
 * Create index for IsPremium fields
 */
function createIndexIsPremium(
  is_premium: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_premium, 'is_premium'),
  ];

  return {
    fields: ['is_premium'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default LifestyleContentORM;